# Generated by Django 5.0.6 on 2024-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=20)),
                ('umidade', models.CharField(max_length=20)),
            ],
        ),
    ]
