# Generated by Django 5.0.6 on 2024-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estufa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estufa',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estufa',
            name='setor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estufa',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estufa',
            name='temperatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estufa',
            name='umidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
