# Generated by Django 5.0.6 on 2024-08-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estufa', '0002_estufa_descricao_estufa_setor_alter_estufa_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estufa',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='estufa',
            name='umidade',
        ),
    ]
